# @package _group_

batch_size: 32
dev_batch_size: 64
adam_eps: 1e-8
adam_betas: (0.9, 0.999)
max_grad_norm: 1.0
log_batch_step: 400
train_rolling_loss_step: 400
weight_decay: 0.0
learning_rate: 1e-5

# Linear warmup over warmup_steps.
warmup_steps: 1000

# Number of updates steps to accumulate before performing a backward/update pass.
gradient_accumulation_steps: 1

# Total number of training epochs to perform.
num_train_epochs: 10
eval_per_epoch: 1
hard_negatives: 0
other_negatives: 1
val_av_rank_hard_neg: 40
val_av_rank_other_neg: 40
val_av_rank_bsz: 32
val_av_rank_max_qs: 10000